// Generated by CoffeeScript 1.6.3
(function() {
  var socket;

  socket = io.connect("http://localhost:3333");

  socket.on("news", function(data) {
    return console.log(data);
  }, socket.emit("return msg", {
    "Hello": "World",
    "I am": "the user"
  }));

}).call(this);
